steps:
  # Step 3: Run BigQuery query
- name: 'gcr.io/cloud-builders/gcloud'
  id: 'run-query'
  entrypoint: 'bash'
  args:
      - -c
      - |
        bq query --use_legacy_sql=false 'SELECT * FROM iconic-scholar-449915-e6.menaga.student LIMIT 10'
        echo "✅ BigQuery query executed successfully"

# Define the secret manager reference
availableSecrets:
  secretManager:
    - versionName: projects/12182601552/secrets/my-service-account-key/versions/1
      env: 'SERVICE_ACCOUNT_KEY'

options:
  logging: NONE
