steps:
  # Step 1: Fetch the secret and write it to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'fetch-secret'
    secretEnv: ['my-service-account-key']  # Use secret from Secret Manager
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$my-service-account-key" > /workspace/service-account-key.json
        echo "✅ Secret saved to /workspace/service-account-key.json"

  # Step 2: Authenticate using the service account key
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'authenticate'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=/workspace/service-account-key.json
        gcloud config set project $PROJECT_ID
        echo "✅ Authenticated successfully"

  # Step 3: Run BigQuery query
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'run-query'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        bq query --use_legacy_sql=false 'SELECT * FROM iconic-scholar-449915-e6.menaga.student LIMIT 10'
        echo "✅ BigQuery query executed successfully"

# Define the secret manager reference
availableSecrets:
  secretManager:
    - versionName: projects/12182601552/secrets/my-service-account-key/versions/1
      env: 'my-service-account-key'

options:
  logging: NONE
