steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching credentials from Secret Manager..."
        gcloud secrets versions access latest --secret="bigquery-service-account-key" > /workspace/key.json
        gcloud auth activate-service-account --key-file /workspace/key.json
        gcloud config set project $PROJECT_ID
        bq query --nouse_legacy_sql \
          'SELECT * FROM iconic-scholar-449915-e6.menaga.student LIMIT 10;'

options:
  logging: NONE
