steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Fetch the service account key from Secret Manager
        SECRET_KEY=$(gcloud secrets versions access latest --secret="my-service-account-key")

        # Save the secret to a file
        echo $SECRET_KEY > /workspace/service-account-key.json

        # Authenticate with the service account
        gcloud auth activate-service-account --key-file=/workspace/service-account-key.json
        
        # Set the project ID
        gcloud config set project $PROJECT_ID
        
        # Run the BigQuery query
        bq query --use_legacy_sql=false 'SELECT * FROM `iconic-scholar-449915-e6.menaga.student` LIMIT 10'
        
options:
  logging: NONE 
